### PR TITLE
added tic toe game flutter

### PR DESCRIPTION
**Pull request by arpitvermaofficial**
write project name with contributor name

### CODE REVIEW

**Comment by arpitvermaofficial** [comment]
add this with hacktoberfest accepted label

**Review by Aditya-150 — CHANGES_REQUESTED** [review]
Please add a README.md in your project folder. In README.md file provide a brief description about the project and some screenshots if possible.

**Comment by arpitvermaofficial** [comment]
Adding README.md file with proper screenshots

**Review by Aditya-150 — APPROVED** [review]
Awesome👍

**Pull request merged**
