### PR TITLE
Calculator App Using Flutter

### PR DESCRIPTION
**Pull request by LemonDrop847**
# Description

This is a Simple Calculator App made using Flutter.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**Test Configuration**: (If any)
* Firmware version: 
* Hardware:
* Toolchain: Flutter v3.0.5 | Dart v2.17.06
* SDK: Android SDK v33.0.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Aditya-150 — CHANGES_REQUESTED** [review]
projects_Intermediate/APP_DEVELOPMENT/Calculator_App_Nitin`_`Mishra/

Change `_` to `-`. Then its ready to merge.

**Comment by LemonDrop847** [comment]
Renamed!

**Comment by LemonDrop847** [comment]
> projects_Intermediate/APP_DEVELOPMENT/Calculator_App_Nitin`_`Mishra/
> 
> Change `_` to `-`. Then its ready to merge.

Renamed!

**Review by Aditya-150 — APPROVED** [review]
Everything looks great...🙂
Ready to merge🚀

**Pull request merged**
