### PR TITLE
SORT_1 solved using java

### PR DESCRIPTION
**Pull request by soumyaranjan-panda**
# Description
Solved SORT_1 using java

# Question 
You are given an array of 0s and 1s in random order.

# Fixes 

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by arpitapadhy23 — COMMENTED** [review]
There is a compilation error in this solution. Check it once.

**Comment by soumyaranjan-panda** [comment]
# Works fine on my system
Screenshot 2022-10-10 230233

**Comment by shokushwaha** [comment]
please assign this to me.

**Comment by soumyaranjan-panda** [comment]
@arpitapadhy23 can you review this again

**Review by arpitapadhy23 — COMMENTED** [review]
Hey! Still not getting the desired output! Check it in the java compiler once instead of any editor.

**Pull request closed without merging**
