### PR TITLE
Python solution for Maximum_sum

### PR DESCRIPTION
**Pull request by VinWare**
# Description
Solved the MAXIMUM_SUM problem in Python

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pratyush-giri** [comment]
your solution to ANAGRAM question is correct and satisfactory. But you have incorrectly named your solution file to MAXIMUM_SUM.py. make required corrections

**Comment by kartik525** [comment]
@VinWare  code is good and correct .

**Review by yagyandatta — APPROVED** [review]

**Review by yagyandatta — COMMENTED** [review]
@VinWare try different techniques to reduce space complexity.

**Comment by VinWare** [comment]
@pratyush-giri thanks for informing, I'll change the file name and add another PR
@kartik525 thanks for mergin
@yagyandatta sure, but I think it may be better to put different approaches in different Files right? If I put other approaches I'll add them under VinWare folder, but as different names.. and I'll rename the main file in that case

**Pull request merged**
