### PR TITLE
MAXIMUM_SUM

### PR DESCRIPTION
**Pull request by soumyaranjan-panda**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**: (If any)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Aditya-150 — COMMENTED** [review]
Don't add multiple files in a single pull request. Remove those empty files.

**Comment by Aditya-150** [comment]
> # Description
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> 
> Fixes # (issue)
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> **Test Configuration**: (If any)
> 
> * Firmware version:
> * Hardware:
> * Toolchain:
> * SDK:
> 
> # Checklist:
> * [ ]  My code follows the style guidelines of this project
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  Any dependent changes have been merged and published in downstream modules

Describe about what problem you are solving.  Mention the language who have preferred in your pr description. Have any doubts regarding anything you can ask in discussions or simply here.🙂

**Comment by Aditya-150** [comment]
@sattwik21 I have done the review. And suggested changes. You can check.

**Comment by soumyaranjan-panda** [comment]
> Don't add multiple files in a single pull request. Remove those empty files.

how do you pull requests for a single file? Like I tried to pr only maximum_sum

**Comment by Aditya-150** [comment]
> how do you pull requests for a single file? Like I tried to pr only maximum_sum

Just you need to remove all those files and commit the changes. If you want to know how to do that go through [CONTRIBUTION.md](https://github.com/Spectrum-CETB/Spectober_Fest/blob/main/CONTRIBUTION.md).

If still your doubt is not clear go to Discussions tab and  there create a new discussion. Then from select categories select QnA category. Don't forget to add title to it. Then describe your problem and add screenshots if possible. Any one out there can solve problem.

But if you want we can continue discuss about it here.🙂

**Comment by soumyaranjan-panda** [comment]
> > how do you pull requests for a single file? Like I tried to pr only maximum_sum
> 
> Just you need to remove all those files and commit the changes. If you want to know how to do that then go through [CONTRIBUTION.md](https://github.com/Spectrum-CETB/Spectober_Fest/blob/main/CONTRIBUTION.md).
> 
> If still your doubt is not clear go to Discussions tab and there create a new discussion. Then from select categories select QnA category. Don't forget to add title to it. Then describe your problem and add screenshots if possible. Any one out there can solve problem.
> 
> But if you want we can continue discuss about it here.🙂 Meanwhile, I would suggest you to do one pr for one question. I would suggest you to do the next question in a new pr. But its your wish. Just don't forget to add the readme for particular question solution in the folder. Follow [README.md](https://github.com/Spectrum-CETB/Spectober_Fest/blob/main/coding_freshmen/README.md) from coding_freshman folder.

can I have your whatsapp no.

**Comment by soumyaranjan-panda** [comment]
how to pr again???

**Comment by arpitapadhy23** [comment]
> how to pr again???
Kindly go through the Contributing.md file in the main repository. You will get a clear idea. Please go through the rules and regulations once again too.

**Comment by soumyaranjan-panda** [comment]
> > how to pr again???
> > Kindly go through the Contributing.md file in the main repository. You will get a clear idea. Please go through the rules and regulations once again too.

Gone through it still have no idea how to do it I'm stuck at this point

**Comment by Aditya-150** [comment]
Are you in spectrum whatsapp group? I can help you there if possible.

**Pull request closed without merging**
