### PR TITLE
Solved PATTERN_FINDER IN C++

### PR DESCRIPTION
**Pull request by bhagyajit6**
# Description
Solved PATTERN_FINDER in C++.

**Test Configuration**: (If any)
* Firmware version: C++ 17
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Aditya-150 — CHANGES_REQUESTED** [review]
Something is wrong leaving it to you. Run your code to find it.🙃

**Comment by Aditya-150** [comment]
@lizapatra220 review it

**Review by lizapatra220 — COMMENTED** [review]
good

**Comment by lizapatra220** [comment]
@bhagyajit6 keep it up.

**Pull request merged**
