### PR TITLE
Br2

### LINKED ISSUE #9: Python Development Project submission guidelines
### Readme Creation👷
Create a `README.md` file in your folder, example `Peter_Solutions/README.md` and add the required packages to be installed before running the program. 
Below are the points that are to be properly mentioned in your readme.

#### 1. Project Explanation with Title🚀
Describe the explanation in your words with a proper title of the project, which can be too precise and short. 

#### 2. Problem Solving🤯
* Try to mention your project plans and implementation.
* Be precise and try to maintain the required factors.

#### 3.  Mention the Tech - Stack 👨‍💻👩‍💻
Be precise and be as clear as possible with your tech - stack

### Project submission 
based on the level and complicacy of the projects ,you are advised to add your project folder for eg:- `YOUR_NAME/xyz.py` to the 
to the respective `projects_Intermediate/PYTHON_DEVELOPEMENT` or `projects_Advanced/PYTHON_DEVELOPEMENT` .
Your folder should contain following information:-
*  The `requirements.txt` file
*  The `.gitignore` file
*  The  `python src ` file

The deciding factors for the level of your projects solely depends upon the technical stacks used in it. Below are some level 
specific projects similar to which your projects will be considered or else will be rejected .
#### `Intermediate level` example
* TIC TAC TOE GAME
* ROCK PAPER SCISSORS
* GUI CALCULATOR

#### `Advanced level` example
* CHATBOT
* FACE MASK DETECTION

### Suggestion if any 📝
Tell us what better can be implemented

If new can refer to the following instructions and start contribution [Contribution Guide](https://github.com/Spectrum-CETB/Spectober_Fest/blob/main/CONTRIBUTION.md) 🤝

### PR DESCRIPTION
**Pull request by KingFire25**
# Description
It is a simple GUI calculator.
Required modules tkinter , functools.

## Added the files for a GUI Calculator

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Aditya-150** [comment]
#9 Issue was not supposed to fixed.
Pls close this pr and make another.
Then it can be definitely be reviewed.

**Comment by KingFire25** [comment]
Should I push directly without mentioning the issue?

**Comment by KingFire25** [comment]
> #9 Issue was not supposed to be fixed. Label `not-to-be-fixed` was added there. You can check. Pls close this pr and make another. Then it can be definitely be reviewed.

I have removed the issue tag you can merge it now I suppose?

**Comment by Aditya-150** [comment]
> I have removed the issue tag you can merge it now I suppose?
Thanks for removing the issue tag. Your PR will be review and merged soon.

**Comment by Aditya-150** [comment]
> Thanks for removing the issue tag. I just had totally forgotten about that. Thanks for reminding also. One more thing you are trying to push more than one problem solution and a project at the same time. Pls make different prs for different problems and projects. As the there are particular maintainer handling particular topic so it creates unnecessary confusion among the maintainers.
> 
> @SAP-20 Pls review this PR.

And sorry😅 for asking you to close the pr I shouldn't have asked that as required changes can be made in this pr.

**Comment by KingFire25** [comment]
Why this branch hasn't been merged yet....Is there any problem?

**Comment by its-navneet** [comment]
Well done. keep it up!

**Pull request merged**
