### PR TITLE
sort_1

### PR DESCRIPTION
**Pull request by heyswayam**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**: (If any)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Aditya-150 — CHANGES_REQUESTED** [review]
**coding_freshmen/C/heySwayam/`sort_1`.md**
The above file name is wrong. Pls make it `README`.md .

The correct format should look like this👇
**coding_freshmen/C/heySwayam/README.md**

**Comment by heyswayam** [comment]
I have made all my files like that , and one has also got accepted
Still i will do the changes, and make a new pr
But i don't think that's the issue

**Comment by Aditya-150** [comment]
You don't have to make a new pr just change the file name and commit it . It will show in your pr.

**Review by lizapatra220 — APPROVED** [review]

**Review by lizapatra220 — COMMENTED** [review]
plz write the correct format for readme file

**Comment by Aditya-150** [comment]
@lizapatra220 the issue is solved. Now can review it again.

**Review by lizapatra220 — APPROVED** [review]

**Pull request merged**
