### PR TITLE
Added TYPING SPEED Calculator Python Project

### PR DESCRIPTION
**Pull request by KuSantosh100**
# Description

This is a Python project for Calculating Keyboard Typing Speed. 
After typing through each letter correctly it will show your typing speed in WPM(words per minute) in the end.
Do Give It A Try!! 

**Test Configuration**: (If any)
* Firmware version: Python 3.10
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KuSantosh100** [comment]
Can anyone please check out this code base/project for review and merge it into the main repository?
@Aditya-150

**Comment by Aditya-150** [comment]
Ok wait. I have requested a review he will be reviewing it soon.

**Review by sattwik21 — APPROVED** [review]

**Comment by Aditya-150** [comment]
👍

**Comment by sattwik21** [comment]
Nice work dude

**Comment by KuSantosh100** [comment]
> Nice work dude

Thank You @sattwik21 Sir and  @Aditya-150  Sir.

**Pull request merged**
